name: Building documentation as gh-pages
on:
  push:
    branches:
    - main

jobs:
  build_docs:
    name: documentation
    runs-on: ubuntu-latest # ${{ matrix.platform }}

    steps:
      # Checkout the repository and setups the machine to use python
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: generates API documentation
        # This step may not run all the time if the documentation is changed manually
        run: |
          pip install sphinx
          cd docs
          sphinx-apidoc -o . ../sagittal_average
      - name: Build and Commit
        uses: sphinx-notes/pages@v2
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
